### ISSUE TITLE
Parsed SPL data not public?

### ISSUE THREAD

**Issue by pdahlberg** [cryptoplease/cryptoplease-dart#109]
I'm trying to get NFT Metplex data. However all classes with the parsed SPL account data seems to be private. 

What path do I take from the `getTokenAccountsByOwner` result to reach it's data?

**Comment by iharobCP** [comment]
Hi. No, the SPL token account data is not private. It's just too deeply nested into the response just like it is in the actual response from the RPC endpoint.

In fact we already did some stuff for metaplex, but we are going to make it public next week. So if you have the time and can wait, you can take advantage of it.

If you want to try it yourself. It is not that hard. After getting the token accounts by means of `getTokenAccountsByOwner()`  you can do something like this

```    
    final nftMints = accounts
        .map((item) {
          final data = item.account.data?.maybeMap(
            splToken: (splToken) => splToken.parsed,
            orElse: () => null,
          );

          if (data != null) {
            final info = data.info;
            final amount = info.tokenAmount;

            if (amount.decimals == 0) {
              return info.mint;
            } else {
              return null;
            }
          } else {
            return null;
          }
        })
        .whereType<String>()
        .toList(growable: false);

    final unfiltered = await Future.wait(
      nftMints.map(
        (mint) => Metadata.fromMint(
          solanaClient: _solanaClient,
          mint: mint,
        ),
      ),
    );

    // Remove nulls
    return unfiltered.whereType<Metadata>().toList(growable: false).toList();
```
Then a simple way to get the metadata would be:

```
static Future<Metadata?> fromMint({
    required RPCClient solanaClient,
    required String mint,
  }) async {
    final programAddress = await findProgramAddress(
      seeds: [
        'metadata'.codeUnits,
        Buffer.fromBase58(_metaplexMetadataProgramId),
        Buffer.fromBase58(mint),
      ],
      programId: _metaplexMetadataProgramId,
    );
    final account = await solanaClient.getAccountInfo(programAddress);
    if (account == null) {
      return null;
    }

    final data = account.data;
    if (data == null) {
      return null;
    }

    return data.maybeWhen(
      fromBytes: Metadata.fromBinary,
      orElse: () => null,
    );
  }
```

If `fromMint()` returns `null` it means there is no metadata or that it is not in the correct format.

Of course, you still need to implement the `fromBinary()` constructor. Which is not difficult and you can use some of the stuff that exist already in some github repos as a guide or just directly this [metaplex Architecture](https://github.com/metaplex-foundation/metaplex/blob/master/ARCHITECTURE.md).

I do not share our implementation because it uses some convenience byte readers and that would be just too much to share here.

**Comment by pdahlberg** [comment]
Thanks for the code! I won't have a lot of time this week so I'll just be doing a few experiments with the code you gave me. Btw, is there a branch I can clone with next weeks release to try out the new stuff in advance?

**Comment by TransFormes** [comment]
The fromBinary method is a bit difficult for a novice to implement. Is there a simple example
