### ISSUE TITLE
Layout is broken 

### ISSUE THREAD

**Issue by ookami-kb** [cryptoplease/cryptoplease-dart#468]
**Screenshots**

<img width="300" src="https://user-images.githubusercontent.com/853356/192886948-d7d95e1e-4cbe-452f-9a55-015d870ccbba.PNG" />

**Smartphone (please complete the following information):**
 - Device: iPhone SE 2020
 - OS: iOS 16
 - Version 1.42

**Comment by rhbrunetto** [comment]
I think this was fixed by #532. It's not happening on `master` anymore.

<details><summary>Screenshot</summary>

- Device: iPhone SE 2020
- OS: iOS 16

![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-10-25 at 11 38 28](https://user-images.githubusercontent.com/19499575/197803869-23dad820-3d92-4ca8-814e-34d075c1ae54.png)
</details>
